[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "thin"
opt-level = 3
split-debuginfo = "off"
strip = "symbols"

[target."aarch64-linux-android"]
linker = "clang"
rustflags = [
	"-C", "default-linker-libraries=yes",
	"-C", "linker-plugin-lto",
	"-C", "link-arg=--target=aarch64-linux-android24",
	"-C", "link-arg=-B/data/data/com.termux/files/usr/tmp/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/24",
]

[patch.crates-io]
cranelift-codegen = { path = "/data/data/com.termux/files/home/cranelift-codegen" }
deno_panic = { path = "/data/data/com.termux/files/home/deno_panic" }

[env]
CC = "clang"
CXX = "clang++"
AR = "llvm-ar"
NM = "llvm-nm"
CFLAGS = "--target=aarch64-linux-android24 -O3 -flto=thin -femulated-tls"
CXXFLAGS = "--target=aarch64-linux-android24 -O3 -flto=thin -femulated-tls"
LDFLAGS = "--target=aarch64-linux-android24 -B/data/data/com.termux/files/usr/tmp/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/24"
CXXSTDLIB = "c++_shared"

GN_ARGS = "use_custom_libcxx=false"
